const data = {
  issues: [
    {
      title: "Bug in Login Page",
      description: "Users are unable to log in due to an authentication error.",
      assigned_by: "John Doe",
      created_at: "2023-05-15T10:30:00Z",
      organization_linked_to: "AcmeCorp",
      assigned_to: "Jane Smith",
      repo: "myapp/frontend",
      status: "Open",
      tags: ["bug", "authentication"],
      num_comments: 3,
      issue_number: 123,
    },
    {
      title: "Feature Request: Dark Mode",
      description:
        "Users want a dark mode option for better readability at night.",
      assigned_by: "Alice Johnson",
      created_at: "2023-05-16T14:20:00Z",
      organization_linked_to: "TechInnovators",
      assigned_to: "Bob Brown",
      repo: "myapp/settings",
      status: "In Progress",
      tags: ["feature", "design"],
      num_comments: 5,
      issue_number: 124,
    },
    {
      title: "Bug Report: Missing Images",
      description: "Some images are not loading properly on the product pages.",
      assigned_by: "Chris Anderson",
      created_at: "2024-03-10T09:15:00Z",
      organization_linked_to: "EcommerceSolutions",
      assigned_to: "Emily White",
      repo: "myapp/backend",
      status: "Open",
      tags: ["bug", "frontend"],
      num_comments: 5,
      issue_number: 789,
    },
    {
      title: "Enhancement Request: Social Media Integration",
      description:
        "Add social media sharing buttons to improve user engagement.",
      assigned_by: "Mark Taylor",
      created_at: "2024-02-28T16:20:00Z",
      organization_linked_to: "SocialTechCo",
      assigned_to: "Sophia Brown",
      repo: "myapp/frontend",
      status: "Open",
      tags: ["enhancement", "UI/UX"],
      num_comments: 1,
      issue_number: 987,
    },
    {
      title: "Technical Debt: Refactoring Legacy Code",
      description:
        "Refactor outdated code segments for improved maintainability and performance.",
      assigned_by: "Daniel Martinez",
      created_at: "2024-01-15T11:30:00Z",
      organization_linked_to: "SoftwareSolutionsLtd",
      assigned_to: "Ryan Johnson",
      repo: "myapp/backend",
      status: "Open",
      tags: ["technical debt", "code quality"],
      num_comments: 4,
      issue_number: 654,
    },
    {
      title: "Bug in sign up Page",
      description:
        "Users are unable to sign up due to an authentication error.",
      assigned_by: "Jane Doe",
      created_at: "2023-04-15T10:30:00Z",
      organization_linked_to: "AcmeCorp",
      assigned_to: "John Smith",
      repo: "myapp/backend",
      status: "Closed",
      tags: ["bug", "authentication"],
      num_comments: 3,
      issue_number: 123,
    },
  ],
};

module.exports = data;
